In [1]:
import numpy as np

In [2]:
# Keywords: version, check numpy version, what numpy version am i using, how to find my np version
# Answer: np.__version__
import numpy as np
print(np.__version__)

2.5.1


In [5]:
# Keywords: dtype, data type, check data type, find dtype of array or matrix
# Answer: array.dtype
arr = np.array([1.0, 2.0, 3.0])
print(arr.dtype)

# Keywords: astype, change dtype, convert data type, cast array type, change matrix type
# Answer: array.astype(new_type)
arr = np.array([1, 2, 3])
float_arr = arr.astype(np.float64)
print(float_arr)

float64
[1. 2. 3.]


In [7]:
# Keywords: zero, zeros, how do i make a matrix of zeros, create zero array
# Answer: np.zeros(shape)
print(np.zeros((3, 3)))

# Keywords: zeros_like, match shape zeros, create zeros with same shape as another array
# Answer: np.zeros_like(array)
arr = np.array([[1, 2], [3, 4]])
print(np.zeros_like(arr))

# Keywords: ones, matrix of ones, how do i make an array of ones
# Answer: np.ones(shape)
print(np.ones((2, 4)))

# Keywords: ones_like, match shape ones, create ones with same shape as another array
# Answer: np.ones_like(array)
arr = np.array([[1, 2], [3, 4]])
print(np.ones_like(arr))

# Keywords: eye, 2D array with ones on diagonal, identity matrix with offset, 2d diagonal matrix
# Answer: np.eye(N, M=None, k=0)
#M = number of columns (optional, defaults to N)
# k = index of the diagonal (0 for main diagonal, positive for upper, negative for lower)
print(np.eye(3))

# Keywords: identity, square identity matrix, create identity matrix
# Answer: np.identity(n)
print(np.identity(3))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0]
 [0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1]
 [1 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# Keywords: boolean indexing, filter array, find elements satisfying condition, condition mask
# Answer: array[condition]
arr = np.array([10, 25, 30, 45, 50])
result = arr[arr > 25]
print(result)

# Keywords: where, find indices satisfying condition, get index of elements meeting condition
# Answer: np.where(condition)
arr = np.array([10, 25, 30, 45, 50])
indices = np.where(arr > 25)
print(indices)

# Keywords: conditional replacement, replace elements satisfying condition, select or replace based on condition
# Answer: np.where(condition, x, y)
arr = np.array([10, 25, 30, 45, 50])
result = np.where(arr > 25, arr, 0)
print(result)

[30 45 50]
(array([2, 3, 4]),)
[ 0  0 30 45 50]


In [9]:
# Keywords: select, multiple conditions, if elif else, choose values by multiple conditions, color scheme grading
# Answer: np.select(condlist, choicelist, default)
arr = np.array([20, 50, 75, 88, 98])

conditions = [
    arr < 33,
    (arr >= 33) & (arr < 75),
    (arr >= 75) & (arr <= 95),
    arr > 95
]

choices = ['red', 'yellow', 'blue', 'green']

colors = np.select(conditions, choices, default='gray')
print(colors)

['red' 'yellow' 'blue' 'blue' 'green']


In [12]:
# Keywords: vstack, vertical stack, concatenate rows, stack arrays vertically
# Answer: np.vstack((arr1, arr2))
a = np.array([1, 2])
b = np.array([3, 4])
print(np.vstack((a, b)))

# Keywords: hstack, horizontal stack, concatenate columns, stack arrays horizontally
# Answer: np.hstack((arr1, arr2))
a = np.array([1, 2])
b = np.array([3, 4])
print(np.hstack((a, b)))

# Keywords: dstack, depth stack, stack along third axis, 3d stack
# Answer: np.dstack((arr1, arr2))
a = np.array([[1], [2]])
b = np.array([[3], [4]])
print(np.dstack((a, b)))

# Keywords: stack, stack along new axis, join arrays along specified axis
# Answer: np.stack((arr1, arr2), axis=0)
a = np.array([1, 2])
b = np.array([3, 4])
print(np.stack((a, b), axis=0))

# Keywords: column_stack, stack 1d arrays as columns, 2d array from 1d columns
# Answer: np.column_stack((arr1, arr2))
a = np.array([1, 2])
b = np.array([3, 4])
print(np.column_stack((a, b)))

# Keywords: row_stack, stack 1d arrays as rows, 2d array from 1d rows
# Answer: np.r_((arr1, arr2))
a = np.array([1, 2])
b = np.array([3, 4])
# Alternative using r_ operator:
print(np.r_[a, b])

# Keywords: concatenate, combine arrays, join arrays along existing axis
# Answer: np.concatenate((arr1, arr2), axis=0)
a = np.array([[1, 2]])
b = np.array([[3, 4]])
print(np.concatenate((a, b), axis=0))

[[1 2]
 [3 4]]
[1 2 3 4]
[[[1 3]]

 [[2 4]]]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3 4]
[[1 2]
 [3 4]]


In [13]:
# Keywords: flatten, convert matrix to 1d array, flatten array copy
# Answer: array.flatten(order='C')
arr = np.array([[1, 2], [3, 4]])
flat = arr.flatten()
print(flat)

# Keywords: ravel, 1d view of array, reshape to 1d memory efficient
# Answer: array.ravel(order='C')
arr = np.array([[1, 2], [3, 4]])
rav = arr.ravel()
print(rav)

# Keywords: reshape -1, flatten using reshape, convert to 1d using reshape
# Answer: array.reshape(-1)
arr = np.array([[1, 2], [3, 4]])
reshaped = arr.reshape(-1)
print(reshaped)

# Keywords: flat iterator, iterate 1d over multidimensional array, 1d array iterator
# Answer: array.flat
arr = np.array([[1, 2], [3, 4]])
print(list(arr.flat))

# Keywords: difference between flatten and ravel, copy vs view flatten
# Answer: flatten() returns a copy (modifying it does not affect original), ravel() returns a view (modifying it changes original)
arr = np.array([[1, 2], [3, 4]])
r = arr.ravel()
r[0] = 99
print(arr)

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[np.int64(1), np.int64(2), np.int64(3), np.int64(4)]
[[99  2]
 [ 3  4]]


In [14]:
# Keywords: ndim, number of dimensions, check dimensions of array or matrix
# Answer: array.ndim
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)

# Keywords: shape, matrix dimensions, rows and columns count, size of dimensions
# Answer: array.shape
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

# Keywords: size, total elements count, number of elements in array
# Answer: array.size
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.size)

# Keywords: itemsize, memory size per element, byte size of single element
# Answer: array.itemsize
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64)
print(arr.itemsize)

# Keywords: nbytes, total memory size, total bytes used by array
# Answer: array.nbytes
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64)
print(arr.nbytes)

# Keywords: dtype, data type of elements, array element type
# Answer: array.dtype
arr = np.array([1, 2, 3])
print(arr.dtype)

2
(2, 3)
6
8
48
int64


In [15]:
# Keywords: diag, extract diagonal, create diagonal matrix, get main diagonal
# Answer: np.diag(v, k=0)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.diag(arr))

# Keywords: create diagonal matrix, 2d array from 1d diagonal
# Answer: np.diag(1d_array)
vec = np.array([1, 2, 3])
print(np.diag(vec))

# Keywords: diagonal, extract diagonal multi-dimensional, get diagonal along axes
# Answer: array.diagonal(offset=0, axis1=0, axis2=1)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.diagonal())

# Keywords: diagflat, create 2d array from flat input, diagonal matrix from flattened array
# Answer: np.diagflat(v, k=0)
print(np.diagflat([1, 2, 3]))

# Keywords: fill_diagonal, modify diagonal in place, set diagonal elements to value
# Answer: np.fill_diagonal(a, val)
arr = np.zeros((3, 3), dtype=int)
np.fill_diagonal(arr, 5)
print(arr)

# Keywords: trace, sum of diagonal elements, trace of matrix
# Answer: np.trace(a) or array.trace()
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.trace(arr))

# Keywords: triu, upper triangle of matrix, zero out lower triangle
# Answer: np.triu(m, k=0)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.triu(arr))

# Keywords: tril, lower triangle of matrix, zero out upper triangle
# Answer: np.tril(m, k=0)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.tril(arr))

[1 5 9]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[1 5 9]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[5 0 0]
 [0 5 0]
 [0 0 5]]
15
[[1 2 3]
 [0 5 6]
 [0 0 9]]
[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [16]:
# Keywords: offset parameter, k parameter in diagonal, shift diagonal up or down, upper lower offset diagonal
# Answer: The 'k' (or 'offset') parameter shifts the diagonal: k > 0 moves above main diagonal, k < 0 moves below
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

# k > 0: Offset above the main diagonal
print(np.diag(arr, k=1))

# k < 0: Offset below the main diagonal
print(np.diag(arr, k=-1))

# Works identically when building diagonal matrices:
print(np.diag([10, 20], k=1))

[2 6]
[4 8]
[[ 0 10  0]
 [ 0  0 20]
 [ 0  0  0]]


In [17]:
# Keywords: non main diagonal, get anti diagonal, secondary diagonal, reverse diagonal, offset anti diagonal
# Answer: Flip matrix horizontally with np.fliplr() then use np.diag() with parameter k (k>0 for upper, k<0 for lower)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Main anti-diagonal (top-right to bottom-left)
print(np.diag(np.fliplr(arr)))

# Offset above the main anti-diagonal (k > 0)
print(np.diag(np.fliplr(arr), k=1))

# Offset below the main anti-diagonal (k < 0)
print(np.diag(np.fliplr(arr), k=-1))

[3 5 7]
[2 4]
[6 8]


In [18]:
# Keywords: fliplr, flip left right, flip matrix horizontally, reverse columns
# Answer: np.fliplr(m)
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.fliplr(arr))

# Keywords: flipud, flip up down, flip matrix vertically, reverse rows
# Answer: np.flipud(m)
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.flipud(arr))

# Keywords: flip, flip along specific axis, reverse array along axis
# Answer: np.flip(m, axis=None)
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.flip(arr, axis=1))  # Flips horizontally (same as fliplr)

# Keywords: flip both axes, reverse both rows and columns, 180 degree rotation
# Answer: np.flip(m)
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.flip(arr))

# Keywords: rot90, rotate matrix 90 degrees, counter clockwise rotation
# Answer: np.rot90(m, k=1)
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.rot90(arr, k=1))  # Rotates 90 degrees counter-clockwise

[[3 2 1]
 [6 5 4]]
[[4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]]
[[6 5 4]
 [3 2 1]]
[[3 6]
 [2 5]
 [1 4]]


In [19]:
# Keywords: rot90 k parameter, rotate matrix multiple times, direction of rotation rot90
# Answer: k specifies the number of 90-degree rotations (k>0 is counter-clockwise, k<0 is clockwise)
arr = np.array([[1, 2], 
                [3, 4]])

# k = 1: 90 degrees counter-clockwise
print(np.rot90(arr, k=1))

# k = 2: 180 degrees rotation
print(np.rot90(arr, k=2))

# k = -1: 90 degrees clockwise
print(np.rot90(arr, k=-1))

[[2 4]
 [1 3]]
[[4 3]
 [2 1]]
[[3 1]
 [4 2]]


In [ ]:
# Keywords: seed, random seed, reproducibility, repeatable random numbers
# Answer: np.random.seed(seed) or np.random.default_rng(seed)
np.random.seed(42)  # Legacy method
rng = np.random.default_rng(42)  # Modern recommended Generator instance

# Keywords: rand, uniform distribution 0 to 1, float random array
# Answer: np.random.rand(d0, d1, ...) or rng.random(size)
print(np.random.rand(2, 3))

# Keywords: randn, standard normal distribution, Gaussian random numbers, mean 0 variance 1
# Answer: np.random.randn(d0, d1, ...) or rng.standard_normal(size)
print(np.random.randn(2, 3))

# Keywords: randint, random integers, uniform discrete random integers
# Answer: np.random.randint(low, high, size, dtype) or rng.integers(low, high, size)
print(np.random.randint(low=1, high=10, size=(2, 3)))

# Keywords: choice, random selection, random sample from array, sample with without replacement
# Answer: np.random.choice(a, size, replace=True, p=None) or rng.choice(a, size, replace, p)
arr = np.array(['A', 'B', 'C', 'D'])
print(np.random.choice(arr, size=2, replace=False, p=[0.1, 0.2, 0.3, 0.4]))

# Keywords: shuffle, in place random shuffle, randomize array order
# Answer: np.random.shuffle(x) or rng.shuffle(x)
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

# Keywords: permutation, random permutation copy, shuffle array without modifying original
# Answer: np.random.permutation(x) or rng.permutation(x)
arr = np.array([1, 2, 3, 4, 5])
permuted = np.random.permutation(arr)
print(permuted)

# Keywords: normal distribution, Gaussian distribution with custom mean and std
# Answer: np.random.normal(loc, scale, size) or rng.normal(loc, scale, size)
print(np.random.normal(loc=10.0, scale=2.0, size=(2, 2)))

# Keywords: uniform distribution, floating point random numbers within range
# Answer: np.random.uniform(low, high, size) or rng.uniform(low, high, size)
print(np.random.uniform(low=5.0, high=15.0, size=(2, 2)))